"""ROS-free AirSim and ArduPilot SITL lifecycle support."""

from .airsim_settings import AirSimSettings
from .config import (
    AIRSIM_VERSION,
    ARDUPILOT_COMMIT,
    ARDUPILOT_MODEL,
    DEFAULT_M1_PARAMETER_FILE,
    AirSimProcessConfig,
    ArduPilotBuild,
    InitialPoseNed,
    MavlinkUdpEndpoint,
    SimulationConfigError,
    SimulationLaunchConfig,
    SimulationPaths,
    SitlHome,
    SitlInstanceConfig,
    airsim_control_port,
    airsim_sensor_port,
    discover_windows_host_ipv4,
    discover_wsl_ipv4,
    mavlink_udp_port,
)
from .fixed_mission import (
    FixedMissionBatchResult,
    FixedMissionResult,
    FixedMissionRunner,
    MissionBatchState,
    MissionEvidenceJournal,
    MissionEvidenceJournalError,
    MissionStepEvidence,
    MissionTerminalState,
    command_result_dict,
    mission_result_dict,
)
from .fault_injection import (
    NavigationFaultInjection,
    NavigationFaultInjector,
    NavigationFaultType,
)
from .lifecycle import (
    ProcessEvidence,
    RuntimeState,
    SimulationLifecycleError,
    SimulationRuntime,
    parse_parameter_file,
    read_git_head,
    sitl_argv,
    validate_m1_parameters,
    windows_path_from_wsl,
)
from .trajectory_recording import NavigationTrajectoryRecorder

__all__ = [
    "AIRSIM_VERSION",
    "ARDUPILOT_COMMIT",
    "ARDUPILOT_MODEL",
    "DEFAULT_M1_PARAMETER_FILE",
    "AirSimProcessConfig",
    "AirSimSettings",
    "ArduPilotBuild",
    "FixedMissionBatchResult",
    "FixedMissionResult",
    "FixedMissionRunner",
    "InitialPoseNed",
    "MavlinkUdpEndpoint",
    "MissionBatchState",
    "MissionEvidenceJournal",
    "MissionEvidenceJournalError",
    "MissionStepEvidence",
    "MissionTerminalState",
    "NavigationFaultInjection",
    "NavigationFaultInjector",
    "NavigationFaultType",
    "NavigationTrajectoryRecorder",
    "ProcessEvidence",
    "RuntimeState",
    "SimulationConfigError",
    "SimulationLifecycleError",
    "SimulationLaunchConfig",
    "SimulationPaths",
    "SimulationRuntime",
    "SitlHome",
    "SitlInstanceConfig",
    "airsim_control_port",
    "airsim_sensor_port",
    "command_result_dict",
    "discover_windows_host_ipv4",
    "discover_wsl_ipv4",
    "mavlink_udp_port",
    "mission_result_dict",
    "parse_parameter_file",
    "read_git_head",
    "sitl_argv",
    "validate_m1_parameters",
    "windows_path_from_wsl",
]
