"""Planned skills that can be developed independently by sub-teams."""

from .base import SkillSpec


SKILLS = [
    SkillSpec(
        name="PlanningSkill",
        label="路径规划",
        intent="move_to",
        type="soft",
        risk_level="high",
        description="将自然语言目标转成 /autonomy/goal，由底层自主避障生成并执行平滑轨迹。",
        example_task="飞到前方20米",
        tools=["get_odometry", "publish_autonomy_goal"],
        enabled=True,
    ),
    SkillSpec(
        name="HoverSkill",
        label="悬停保持",
        intent="hover",
        type="hard",
        risk_level="medium",
        description="发布零速度到 /control/cmd_vel，让无人机进入悬停/停止运动状态。",
        example_task="原地悬停",
        tools=["get_drone_state", "publish_cmd_vel_zero"],
        enabled=True,
    ),
    SkillSpec(
        name="ReturnHomeSkill",
        label="返航",
        intent="return_home",
        type="hard",
        risk_level="high",
        description="调用 /control/return_home 触发 PX4 原生 RTL 返航。",
        example_task="返航并降落",
        tools=["get_drone_state", "return_home"],
        enabled=True,
    ),
    SkillSpec(
        name="EmergencyStopSkill",
        label="急停",
        intent="emergency_stop",
        type="hard",
        risk_level="high",
        description="取消自主目标、发布零速度，并尝试调用 /control/arm 加锁。",
        example_task="立即急停",
        tools=["cancel_autonomy_goal", "publish_cmd_vel_zero", "disarm_drone"],
        enabled=True,
    ),
    SkillSpec(
        name="PerceptionSkill",
        label="环境感知",
        intent="perception",
        type="perception",
        risk_level="low",
        description="读取 RGB、深度、LiDAR 或 detection 摘要，分析前方障碍物风险。",
        example_task="检查前方有没有障碍物",
        tools=["get_camera_summary", "get_lidar_summary", "get_detections"],
        enabled=True,
    ),
    SkillSpec(
        name="CaptureImageSkill",
        label="拍照取证",
        intent="capture_image",
        type="perception",
        risk_level="low",
        description="调用 /perception/capture_image 保存当前 RGB 相机帧并返回文件路径。",
        example_task="拍一张前方照片",
        tools=["capture_image"],
        enabled=True,
    ),
    SkillSpec(
        name="ScanAreaSkill",
        label="区域扫描",
        intent="scan_area",
        type="soft",
        risk_level="medium",
        description="基于当前 RGB、深度、LiDAR 和 detection 缓存生成区域扫描摘要。",
        example_task="扫描前方区域并报告障碍物",
        tools=["get_depth_summary", "get_lidar_summary", "get_detections"],
        enabled=True,
    ),
    SkillSpec(
        name="TargetSearchSkill",
        label="目标搜索",
        intent="search_target",
        type="soft",
        risk_level="medium",
        description="根据自然语言目标匹配当前 detection，例如中文“人”会映射到 YOLO 的 person。",
        example_task="检测人",
        tools=["get_detections", "get_camera_summary", "match_target"],
        enabled=True,
    ),
    SkillSpec(
        name="SemanticImageSkill",
        label="图像语义分析",
        intent="semantic_image",
        type="perception",
        risk_level="low",
        description="调用 /perception/analyze_image，让视觉语言模型或规则感知摘要分析当前 RGB 画面。",
        example_task="分析当前画面中有什么",
        tools=["analyze_image", "get_camera_summary", "get_detections"],
        enabled=True,
    ),
    SkillSpec(
        name="MissionSequenceSkill",
        label="复合任务",
        intent="mission_sequence",
        type="soft",
        risk_level="high",
        description="将起飞、相对移动、目标检测等自然语言复合任务拆成多步执行链。",
        example_task="起飞，向左飞20米，并检测人",
        tools=["takeoff_drone", "publish_autonomy_goal", "match_target"],
        enabled=True,
    ),
    SkillSpec(
        name="MissionReportSkill",
        label="任务报告",
        intent="mission_report",
        type="soft",
        risk_level="low",
        description="汇总飞行状态、工具调用、检测结果和任务结论。",
        example_task="生成当前任务报告",
        tools=["get_drone_state", "get_odometry", "summarize_logs"],
        enabled=True,
    ),
]
