"""Authenticated, resource-bounded WebSocket communication primitives."""

from .protocol import (
    AuthenticationError,
    ClientHello,
    ClientProof,
    ProtocolError,
    ServerChallenge,
    SessionAccepted,
    SignedMessageFrame,
    authentication_proof,
    decode_handshake_frame,
    decode_signed_message,
    encode_frame,
    encode_signed_message,
    verify_authentication_proof,
)
from .queue import BoundedLatestQueue, QueueClosed
from .serial_transport import (
    AsyncByteStream,
    ByteStreamFactory,
    PySerialByteStream,
    ReliableSerialLink,
    SerialChannelClosed,
    SerialDeliveryError,
    SerialDirection,
    SerialFrame,
    SerialFrameDecoder,
    SerialFrameKind,
    SerialLinkStats,
    SerialMessageChannel,
    SerialOnboardChannelFactory,
    SerialTransportError,
    encode_serial_frame,
    payload_requires_delivery,
)

__all__ = [
    "AuthenticationError",
    "AsyncByteStream",
    "BoundedLatestQueue",
    "ByteStreamFactory",
    "ClientHello",
    "ClientProof",
    "ProtocolError",
    "PySerialByteStream",
    "QueueClosed",
    "ReliableSerialLink",
    "ServerChallenge",
    "SessionAccepted",
    "SignedMessageFrame",
    "SerialChannelClosed",
    "SerialDeliveryError",
    "SerialDirection",
    "SerialFrame",
    "SerialFrameDecoder",
    "SerialFrameKind",
    "SerialLinkStats",
    "SerialMessageChannel",
    "SerialOnboardChannelFactory",
    "SerialTransportError",
    "authentication_proof",
    "decode_handshake_frame",
    "decode_signed_message",
    "encode_frame",
    "encode_serial_frame",
    "encode_signed_message",
    "payload_requires_delivery",
    "verify_authentication_proof",
]
