"""Versioned messages used by simulation and real vehicles."""

from .codec import ContractError, ContractErrorCode, decode_message, encode_message
from .auth import new_session_challenge, session_proof, sign_message, verify_message_signature
from .ingress import IngressError, IngressErrorCode, IngressGuard, ReceivedMessage
from .models import (
    SCHEMA_VERSION,
    AckStatus,
    CoordinateFrame,
    FormationCommand,
    FormationShape,
    Heartbeat,
    MissionAck,
    SemanticObservation,
    TrajectorySegment,
    VehicleCommand,
    VehicleCommandType,
    Vector3,
    VehicleTelemetry,
    WireMessage,
)
from .twin import (
    TWIN_SCHEMA_VERSION,
    FidelityLevel,
    HealthStatus,
    MetricDirection,
    MetricRecord,
    MissionEdge,
    MissionEdgeKind,
    MissionGraph,
    MissionNode,
    StrategyKind,
    StrategySpec,
    TwinSource,
    TwinLine,
    TwinState,
    TwinStateSet,
    VehicleProfile,
    WorldEvent,
    source_for_runtime_mode,
)
from .identity import (
    IDENTITY_SCHEMA_VERSION,
    AuthorizationProfile,
    AutonomyLevel,
    CapabilityProfile,
    EmbodiedAgentProfile,
    IdentityAttestation,
    IdentityMetadata,
    VehicleIdentityDocument,
)

__all__ = [
    "SCHEMA_VERSION",
    "TWIN_SCHEMA_VERSION",
    "IDENTITY_SCHEMA_VERSION",
    "AckStatus",
    "ContractError",
    "ContractErrorCode",
    "CoordinateFrame",
    "FormationCommand",
    "FormationShape",
    "AuthorizationProfile",
    "AutonomyLevel",
    "CapabilityProfile",
    "EmbodiedAgentProfile",
    "FidelityLevel",
    "HealthStatus",
    "Heartbeat",
    "IngressError",
    "IngressErrorCode",
    "IngressGuard",
    "IdentityAttestation",
    "IdentityMetadata",
    "MissionAck",
    "MetricDirection",
    "MetricRecord",
    "MissionEdge",
    "MissionEdgeKind",
    "MissionGraph",
    "MissionNode",
    "ReceivedMessage",
    "SemanticObservation",
    "TrajectorySegment",
    "StrategyKind",
    "StrategySpec",
    "TwinSource",
    "TwinLine",
    "TwinState",
    "TwinStateSet",
    "VehicleCommand",
    "VehicleCommandType",
    "Vector3",
    "VehicleTelemetry",
    "VehicleIdentityDocument",
    "VehicleProfile",
    "WireMessage",
    "WorldEvent",
    "decode_message",
    "encode_message",
    "new_session_challenge",
    "session_proof",
    "sign_message",
    "source_for_runtime_mode",
    "verify_message_signature",
]
